baseURL = "https://stoplisten.space"
languageCode = "en-us"
title = "Stop, Listen: A Public Art Project"
theme = "hallo"

[Author]
    name = "a public art installation within Banyule City Council"

[params]
    greeting = "Stop, Listen"

